version: '3.9'

services:
  db:
    image: postgres:alpine
    container_name: dashboard
    restart: always
    environment:
      - POSTGRES_DB=dashboard_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345678
    ports:
      - '5433:5432'
    volumes:
      - dashboard:/var/lib/postgresql/data
volumes:
  dashboard: